### ISSUE TITLE
Integrate with composer

### ISSUE THREAD

**Issue by mike-marcacci** [getvero/vero-php#5]
This project could probably use a composer.json file, and would ideally be hosted on [Packagist](https://packagist.org/) to make it play well as a modern PHP dependency. Also, a license file would be useful for more um, enterprisey customers.

Cool tool, btw!

**Comment by chexton** [comment]
Hey @mike-marcacci. Thanks for the kind words.

I don't believe we have any dependencies, so this was super easy. Can you confirm this looks correct and usable for you? https://github.com/getvero/vero-php/pull/6

If so, please leave a comment there, we'll merge and upload to Packagist this afternoon (we have already signed up).

Legend.

**Comment by mike-marcacci** [comment]
Wow, what a fast response! Almost: I think you'll need to tell the autoloader which files to load. Something like this:
```json
{
    "name": "getvero/vero-php",
    "description": "Library for tracking users and event with Vero's communications platform",
    "require": {
        "php": ">=5.3.0"
    },
    "autoload": {
        "classmap": ["vero.php"]
    }
}
```
I'll test it out with our app right now and let you know!

**Comment by chexton** [comment]
Hey Mike, no problems.

Did you get a chance to test it out :)?

--

Chris Hexton, Co-founder

t(us): 650 843 9866

t(au): 0422 723 190

www.getvero.com


Need tips on campaigns that convert? Read our blog
<http://blog.getvero.com?utm_campaign=signature&utm_source=chris&utm_medium=email>
.

**Comment by courseraza** [comment]
Chris, did you ever push this up to Packagist?

**Comment by chexton** [comment]
Hey guys, you can find it here:
https://packagist.org/packages/getvero/vero-php

Thanks!

--

Chris Hexton, Co-founder

t(us): 650 843 9866

t(au): 0422 723 190

www.getvero.com


Need tips on campaigns that convert? Read our blog
<http://blog.getvero.com?utm_campaign=signature&utm_source=chris&utm_medium=email>
.

**Comment by arduanov** [comment]
@chexton please provide autoload section in composer.json, like in @mike-marcacci sample

```
...
    "autoload": {
        "classmap": ["vero.php"]
    }
...
```
Right now developers must add autoload for vero in own projects, it's wrong way

**Comment by chexton** [comment]
@arduanov having merged your PR, do I need to re-submit to Packagist or anything? I assume it pulls through changes automatically.

**Comment by arduanov** [comment]
@chexton Packagist check updates once a week, but you can make git hook to update immediately, [more info](https://packagist.org/about#how-to-update-packages) 

Also you can [create releases](https://help.github.com/articles/creating-releases/) with [semantic versioning](http://semver.org/), for easily version control. Releases automatically fetched by packagist.

**Comment by chexton** [comment]
Should be good now and we've setup the integration to auto-update Packagist with the Git hook. Will see how it goes with the next update.

Thanks for adding the change. :+1:
